import { defineAction } from "astro:actions";
import { and, eq } from "drizzle-orm";
import { z } from "astro/zod";
import { getDrizzle } from "@database/drizzle";
import { serviceMedia } from "@database/schemas";
import { assertServiceInTenant, assertServiceMediaInTenant, assertServicePermission, resolveServiceTenant, serviceOrganizationIdSchema, assertServiceLockOwner } from "./_helpers";
import { auditService, invalidateServicesCache } from "./_helpers";

export const addServiceMedia = defineAction({ input: z.object({ serviceId: z.uuid(), mediaId: z.uuid(), organizationId: serviceOrganizationIdSchema, kind: z.enum(["GALLERY", "DOCUMENT"]).default("GALLERY"), altText: z.string().trim().min(1).max(300), caption: z.string().trim().max(500).optional().nullable(), sortOrder: z.coerce.number().int().min(0).default(0) }), handler: async (input, context) => { const tenant = resolveServiceTenant(input); const user = await assertServicePermission(context, tenant, { service: ["update"] }); await assertServiceInTenant(input.serviceId, tenant); await assertServiceLockOwner(input.serviceId, user.id, context.locals.session?.id); await assertServiceMediaInTenant(input.mediaId, tenant); await getDrizzle().insert(serviceMedia).values({ serviceId: input.serviceId, mediaId: input.mediaId, kind: input.kind, altText: input.altText, caption: input.caption ?? null, sortOrder: input.sortOrder }).onConflictDoUpdate({ target: [serviceMedia.serviceId, serviceMedia.mediaId], set: { kind: input.kind, altText: input.altText, caption: input.caption ?? null, sortOrder: input.sortOrder } }); auditService(context, user.id, "SERVICE_UPDATE", { resource: "serviceMedia", resourceId: input.mediaId, metadata: { serviceId: input.serviceId, action: "ADD" } }); invalidateServicesCache(); return { success: true }; });

export const updateServiceMedia = defineAction({ input: z.object({ serviceId: z.uuid(), mediaId: z.uuid(), organizationId: serviceOrganizationIdSchema, kind: z.enum(["GALLERY", "DOCUMENT"]), altText: z.string().trim().min(1).max(300), caption: z.string().trim().max(500).optional().nullable(), sortOrder: z.coerce.number().int().min(0) }), handler: async (input, context) => { const tenant = resolveServiceTenant(input); const user = await assertServicePermission(context, tenant, { service: ["update"] }); await assertServiceInTenant(input.serviceId, tenant); await assertServiceLockOwner(input.serviceId, user.id, context.locals.session?.id); await assertServiceMediaInTenant(input.mediaId, tenant); await getDrizzle().update(serviceMedia).set({ kind: input.kind, altText: input.altText, caption: input.caption ?? null, sortOrder: input.sortOrder }).where(and(eq(serviceMedia.serviceId, input.serviceId), eq(serviceMedia.mediaId, input.mediaId))); auditService(context, user.id, "SERVICE_UPDATE", { resource: "serviceMedia", resourceId: input.mediaId, metadata: { serviceId: input.serviceId, action: "UPDATE" } }); invalidateServicesCache(); return { success: true }; });

export const removeServiceMedia = defineAction({ input: z.object({ serviceId: z.uuid(), mediaId: z.uuid(), organizationId: serviceOrganizationIdSchema }), handler: async (input, context) => { const tenant = resolveServiceTenant(input); const user = await assertServicePermission(context, tenant, { service: ["update"] }); await assertServiceInTenant(input.serviceId, tenant); await assertServiceLockOwner(input.serviceId, user.id, context.locals.session?.id); await getDrizzle().delete(serviceMedia).where(and(eq(serviceMedia.serviceId, input.serviceId), eq(serviceMedia.mediaId, input.mediaId))); auditService(context, user.id, "SERVICE_UPDATE", { resource: "serviceMedia", resourceId: input.mediaId, metadata: { serviceId: input.serviceId, action: "REMOVE" } }); invalidateServicesCache(); return { success: true }; });