import { defineAction, ActionError } from "astro:actions";
import { and, eq, isNull } from "drizzle-orm";
import { z } from "astro/zod";
import { getDrizzle } from "@database/drizzle";
import { serviceCategories, serviceCategoryTranslations, serviceTags, serviceTagTranslations } from "@database/schemas";
import { assertAcyclicParent } from "@/core/taxonomy";
import { serviceOrganizationIdSchema, assertServicePermission, assertServiceCategoryInTenant, assertServiceTagInTenant, resolveServiceTenant } from "./_helpers";
import { invalidateServicesCache, auditService } from "./_helpers";

const localeSchema = z.enum(["fr", "en", "es", "ar"]);
const slugSchema = z.string().trim().min(1).max(160).regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/);
const categoryInput = z.object({ organizationId: serviceOrganizationIdSchema, locale: localeSchema, name: z.string().trim().min(1).max(120), slug: slugSchema, description: z.string().trim().max(500).optional().nullable(), parentId: z.uuid().optional().nullable(), clearParent: z.boolean().default(false), icon: z.string().trim().max(120).optional().nullable(), color: z.string().trim().max(32).optional().nullable(), sortOrder: z.coerce.number().int().min(0).max(100_000).default(0) });
const tagInput = z.object({ organizationId: serviceOrganizationIdSchema, locale: localeSchema, name: z.string().trim().min(1).max(120), slug: slugSchema, color: z.string().trim().max(32).optional().nullable() });

function tenantCategoryScope(organizationId: string | null) { return organizationId === null ? isNull(serviceCategories.organizationId) : eq(serviceCategories.organizationId, organizationId); }
function tenantTagScope(organizationId: string | null) { return organizationId === null ? isNull(serviceTags.organizationId) : eq(serviceTags.organizationId, organizationId); }
function tenantCategoryTranslationScope(organizationId: string | null) { return organizationId === null ? isNull(serviceCategoryTranslations.organizationId) : eq(serviceCategoryTranslations.organizationId, organizationId); }
function tenantTagTranslationScope(organizationId: string | null) { return organizationId === null ? isNull(serviceTagTranslations.organizationId) : eq(serviceTagTranslations.organizationId, organizationId); }

export const createServiceCategory = defineAction({ input: categoryInput, handler: async (input, context) => {
  const tenant = resolveServiceTenant(input); const user = await assertServicePermission(context, tenant, { serviceCategory: ["create"] }); if (input.parentId) await assertServiceCategoryInTenant(input.parentId, tenant);
  const db = getDrizzle(); const siblings = await db.select({ id: serviceCategories.id, parentId: serviceCategories.parentId }).from(serviceCategories).where(tenantCategoryScope(tenant.organizationId)); assertAcyclicParent(siblings, null, input.parentId ?? null);
  let id = ""; await db.transaction(async (tx) => { const [row] = await tx.insert(serviceCategories).values({ organizationId: tenant.organizationId, parentId: input.parentId ?? null, slug: input.slug, icon: input.icon ?? null, color: input.color ?? null, sortOrder: input.sortOrder }).returning({ id: serviceCategories.id }); id = row.id; await tx.insert(serviceCategoryTranslations).values({ categoryId: row.id, organizationId: tenant.organizationId, locale: input.locale, name: input.name, slug: input.slug, description: input.description ?? null }); });
  auditService(context, user.id, "SERVICE_CATEGORY_CREATE", { resource: "serviceCategories", resourceId: id, metadata: { organizationId: tenant.organizationId, locale: input.locale } }); invalidateServicesCache(); return { id };
} });

export const updateServiceCategory = defineAction({ input: categoryInput.extend({ id: z.uuid() }), handler: async (input, context) => {
  const tenant = resolveServiceTenant(input); const user = await assertServicePermission(context, tenant, { serviceCategory: ["update"] }); await assertServiceCategoryInTenant(input.id, tenant); if (input.parentId) await assertServiceCategoryInTenant(input.parentId, tenant);
  const db = getDrizzle(); const [current] = await db.select({ id: serviceCategories.id, parentId: serviceCategories.parentId, organizationId: serviceCategories.organizationId }).from(serviceCategories).where(and(eq(serviceCategories.id, input.id), tenantCategoryScope(tenant.organizationId))).limit(1); if (!current) throw new ActionError({ code: "NOT_FOUND", message: "Catégorie introuvable." });
  const nextParentId = input.parentId !== undefined ? input.parentId : (input.clearParent ? null : current.parentId); const nodes = await db.select({ id: serviceCategories.id, parentId: serviceCategories.parentId }).from(serviceCategories).where(tenantCategoryScope(tenant.organizationId)); assertAcyclicParent(nodes, input.id, nextParentId ?? null);
  await db.transaction(async (tx) => { await tx.update(serviceCategories).set({ parentId: nextParentId ?? null, icon: input.icon ?? null, color: input.color ?? null, sortOrder: input.sortOrder }).where(and(eq(serviceCategories.id, input.id), tenantCategoryScope(tenant.organizationId))); const [translation] = await tx.select({ id: serviceCategoryTranslations.id }).from(serviceCategoryTranslations).where(and(eq(serviceCategoryTranslations.categoryId, input.id), eq(serviceCategoryTranslations.locale, input.locale), tenantCategoryTranslationScope(tenant.organizationId))).limit(1); if (translation) await tx.update(serviceCategoryTranslations).set({ name: input.name, slug: input.slug, description: input.description ?? null }).where(eq(serviceCategoryTranslations.id, translation.id)); else await tx.insert(serviceCategoryTranslations).values({ categoryId: input.id, organizationId: tenant.organizationId, locale: input.locale, name: input.name, slug: input.slug, description: input.description ?? null }); });
  auditService(context, user.id, "SERVICE_CATEGORY_UPDATE", { resource: "serviceCategories", resourceId: input.id, metadata: { organizationId: tenant.organizationId, locale: input.locale } }); invalidateServicesCache(); return { id: input.id };
} });

export const deleteServiceCategory = defineAction({ input: z.object({ id: z.uuid(), organizationId: serviceOrganizationIdSchema }), handler: async (input, context) => {
  const tenant = resolveServiceTenant(input); const user = await assertServicePermission(context, tenant, { serviceCategory: ["delete"] }); await assertServiceCategoryInTenant(input.id, tenant); const db = getDrizzle(); const child = await db.select({ id: serviceCategories.id }).from(serviceCategories).where(and(eq(serviceCategories.parentId, input.id), tenantCategoryScope(tenant.organizationId))).limit(1); if (child.length) throw new ActionError({ code: "CONFLICT", message: "Cette catégorie possède des sous-catégories." }); await db.delete(serviceCategories).where(and(eq(serviceCategories.id, input.id), tenantCategoryScope(tenant.organizationId))); auditService(context, user.id, "SERVICE_CATEGORY_DELETE", { resource: "serviceCategories", resourceId: input.id, metadata: { organizationId: tenant.organizationId } }); invalidateServicesCache(); return { success: true };
} });

export const createServiceTag = defineAction({ input: tagInput, handler: async (input, context) => {
  const tenant = resolveServiceTenant(input); const user = await assertServicePermission(context, tenant, { serviceTag: ["create"] }); const db = getDrizzle(); let id = ""; await db.transaction(async (tx) => { const [row] = await tx.insert(serviceTags).values({ organizationId: tenant.organizationId, slug: input.slug, color: input.color ?? null }).returning({ id: serviceTags.id }); id = row.id; await tx.insert(serviceTagTranslations).values({ tagId: row.id, organizationId: tenant.organizationId, locale: input.locale, name: input.name, slug: input.slug }); }); auditService(context, user.id, "SERVICE_TAG_CREATE", { resource: "serviceTags", resourceId: id, metadata: { organizationId: tenant.organizationId, locale: input.locale } }); invalidateServicesCache(); return { id };
} });

export const updateServiceTag = defineAction({ input: tagInput.extend({ id: z.uuid() }), handler: async (input, context) => {
  const tenant = resolveServiceTenant(input); const user = await assertServicePermission(context, tenant, { serviceTag: ["update"] }); await assertServiceTagInTenant(input.id, tenant); const db = getDrizzle();
  const [tag] = await db.select({ id: serviceTags.id }).from(serviceTags).where(and(eq(serviceTags.id, input.id), tenantTagScope(tenant.organizationId))).limit(1); if (!tag) throw new ActionError({ code: "NOT_FOUND", message: "Tag introuvable." });
  await db.transaction(async (tx) => { await tx.update(serviceTags).set({ color: input.color ?? null }).where(and(eq(serviceTags.id, input.id), tenantTagScope(tenant.organizationId))); const [translation] = await tx.select({ id: serviceTagTranslations.id }).from(serviceTagTranslations).where(and(eq(serviceTagTranslations.tagId, input.id), eq(serviceTagTranslations.locale, input.locale), tenantTagTranslationScope(tenant.organizationId))).limit(1); if (translation) await tx.update(serviceTagTranslations).set({ name: input.name, slug: input.slug }).where(eq(serviceTagTranslations.id, translation.id)); else await tx.insert(serviceTagTranslations).values({ tagId: input.id, organizationId: tenant.organizationId, locale: input.locale, name: input.name, slug: input.slug }); });
  auditService(context, user.id, "SERVICE_TAG_UPDATE", { resource: "serviceTags", resourceId: input.id, metadata: { organizationId: tenant.organizationId, locale: input.locale } }); invalidateServicesCache(); return { id: input.id };
} });

export const deleteServiceTag = defineAction({ input: z.object({ id: z.uuid(), organizationId: serviceOrganizationIdSchema }), handler: async (input, context) => { const tenant = resolveServiceTenant(input); const user = await assertServicePermission(context, tenant, { serviceTag: ["delete"] }); await assertServiceTagInTenant(input.id, tenant); await getDrizzle().delete(serviceTags).where(and(eq(serviceTags.id, input.id), tenantTagScope(tenant.organizationId))); auditService(context, user.id, "SERVICE_TAG_DELETE", { resource: "serviceTags", resourceId: input.id, metadata: { organizationId: tenant.organizationId } }); invalidateServicesCache(); return { success: true }; });
