import type { AuthTranslations } from '../config';

const services = 'Services';

export default {
  meta: {
    signIn: { title: 'Connexion — Atomic', description: 'Connectez-vous à votre compte.' },
    signUp: { title: 'Inscription — Atomic', description: 'Créez votre compte.' },
    dashboard: { title: 'Tableau de bord — Atomic', description: 'Gérez votre compte et vos organisations.' },
    admin: { title: 'Administration — Atomic', description: 'Panneau d\'administration.' },
    forgotPassword: { title: 'Mot de passe oublié — Atomic', description: 'Réinitialisez votre mot de passe.' },
    resetPassword: { title: 'Réinitialiser le mot de passe — Atomic', description: 'Choisissez un nouveau mot de passe.' },
    verifyEmail: { title: 'Vérification de l\'email — Atomic', description: 'Confirmez votre adresse email.' },
    profile: { title: 'Mon profil — Atomic', description: 'Gérez vos informations personnelles.' },
    organizations: { title: 'Organisations — Atomic', description: 'Gérez vos organisations.' },
  },
  routes: {
    'sign-in': 'connexion', 'sign-up': 'inscription', dashboard: 'tableau-de-bord', admin: 'administration', 'forgot-password': 'mot-de-passe-oublie', 'reset-password': 'reinitialiser-mot-de-passe', 'verify-email': 'verifier-email', profile: 'profil', organizations: 'organisations',
  },
  signIn: { title: 'Bon retour', description: 'Connectez-vous pour accéder à votre espace.', email: 'Email', emailPlaceholder: 'Entrez votre email', password: 'Mot de passe', passwordPlaceholder: 'Entrez votre mot de passe', submit: 'Se connecter', noAccount: 'Pas encore de compte ?', createAccount: 'Créer un compte', forgotPassword: 'Mot de passe oublié ?', success: 'Connexion réussie !' },
  signUp: { title: 'Créer un compte', description: 'Inscrivez-vous pour commencer.', name: 'Nom', namePlaceholder: 'Entrez votre nom', username: 'Nom d\'utilisateur', usernamePlaceholder: 'Choisissez un nom d\'utilisateur', email: 'Email', emailPlaceholder: 'Entrez votre email', password: 'Mot de passe', passwordPlaceholder: 'Choisissez un mot de passe', submit: 'Créer le compte', hasAccount: 'Déjà un compte ?', signInLink: 'Se connecter', success: 'Compte créé avec succès ! Vous pouvez maintenant vous connecter.' },
  dashboard: { welcome: 'Bienvenue', profile: { title: 'Profil', email: 'Email', username: 'Nom d\'utilisateur', role: 'Rôle' }, organizations: { title: 'Organisations', empty: 'Vous ne faites partie d\'aucune organisation.', create: 'Créer une organisation', viewDetails: 'Voir les détails' }, signOut: 'Se déconnecter', editProfile: 'Modifier le profil' },
  admin: {
    title: 'Administration', contentGroup: 'Contenu', localeSwitcher: { title: 'Langues' },
    tabs: { stats: 'Statistiques', users: 'Utilisateurs', organizations: 'Organisations', auditLog: 'Journal d\'audit', roles: 'Rôles', blog: 'Blog', services, site: 'Site', navigation: 'Navigation', pages: 'Pages', media: 'Médias', theme: 'Thème' },
    stats: { totalUsers: 'Utilisateurs', totalOrganizations: 'Organisations', recentSignups: 'Inscriptions récentes', recentSignupsDescription: 'Au cours des 7 derniers jours' },
    users: { searchPlaceholder: 'Rechercher par nom ou email…', columns: { name: 'Nom', email: 'Email', username: 'Utilisateur', role: 'Rôle', status: 'Statut', joined: 'Inscrit le', actions: 'Actions' }, roles: { user: 'Utilisateur', admin: 'Administrateur' }, status: { active: 'Actif', banned: 'Banni' }, actions: { ban: 'Bannir', unban: 'Débannir', setAdmin: 'Passer admin', setUser: 'Passer utilisateur', delete: 'Supprimer', impersonate: 'Se connecter en tant que' }, confirmBan: 'Êtes-vous sûr de vouloir bannir cet utilisateur ?', confirmDelete: 'Êtes-vous sûr de vouloir supprimer cet utilisateur ? Cette action est irréversible.', banned: 'Utilisateur banni.', unbanned: 'Utilisateur débanni.', roleChanged: 'Rôle mis à jour.', deleted: 'Utilisateur supprimé.', noResults: 'Aucun utilisateur trouvé.', sort: { label: 'Trier', nameAsc: 'Nom A→Z', nameDesc: 'Nom Z→A', newest: 'Plus récent', oldest: 'Plus ancien' }, filter: { allRoles: 'Tous les rôles', allStatuses: 'Tous les statuts' } },
    organizations: { searchPlaceholder: 'Rechercher par nom ou slug…', columns: { name: 'Nom', slug: 'Slug', owner: 'Propriétaire', members: 'Membres', created: 'Créée le', actions: 'Actions' }, actions: { delete: 'Supprimer' }, confirmDelete: 'Êtes-vous sûr de vouloir supprimer cette organisation ?', deleted: 'Organisation supprimée.', noResults: 'Aucune organisation trouvée.', sort: { label: 'Trier', nameAsc: 'Nom A→Z', nameDesc: 'Nom Z→A', newest: 'Plus récente', oldest: 'Plus ancienne', mostMembers: 'Plus de membres' } },
    auditLog: { columns: { date: 'Date', user: 'Utilisateur', action: 'Action', resource: 'Ressource', ip: 'Adresse IP' }, filterAction: 'Filtrer par action', allActions: 'Toutes les actions', noResults: 'Aucun événement trouvé.', showMore: 'Charger plus' },
    roles: { title: 'Rôles & Permissions', description: 'Matrice des permissions par rôle', globalRoles: 'Rôles globaux', orgRoles: 'Rôles d\'organisation', resource: 'Ressource', permissions: 'Permissions', roleName: { admin: 'Administrateur', editor: 'Éditeur', user: 'Utilisateur', owner: 'Propriétaire', orgAdmin: 'Admin org.', member: 'Membre' }, resourceName: { page: 'Pages', section: 'Sections', media: 'Médias', site: 'Site', navigation: 'Navigation', audit: 'Audit', theme: 'Thème', user: 'Utilisateurs', session: 'Sessions', organization: 'Organisations', member: 'Membres', invitation: 'Invitations', team: 'Équipes', ac: 'Contrôle d\'accès' }, systemPermissions: 'Toutes les permissions (détails système)', customRoles: 'Rôles personnalisés', customRolesDescription: 'Gérez les rôles personnalisés pour les organisations.', selectOrg: 'Sélectionner une organisation', noOrgs: 'Aucune organisation trouvée.', noCustomRoles: 'Aucun rôle personnalisé pour cette organisation.', createRole: 'Créer un rôle', editRole: 'Modifier', deleteRole: 'Supprimer', roleNameLabel: 'Nom du rôle', roleNamePlaceholder: 'ex: reviewer, content-manager', permissionsLabel: 'Permissions', confirmDelete: 'Supprimer ce rôle ? Cette action est irréversible.', created: 'Rôle créé.', updated: 'Rôle mis à jour.', deleted: 'Rôle supprimé.', save: 'Enregistrer', cancel: 'Annuler' },
    impersonation: { banner: 'Vous êtes connecté en tant que {name}', stop: 'Arrêter l\'emprunt d\'identité' },
    cms: { site: { title: 'Paramètres du site', description: 'Gérez les informations générales, réseaux sociaux, contact et horaires.' }, navigation: { title: 'Navigation', description: 'Gérez les menus et éléments de navigation.' }, pages: { title: 'Pages', description: 'Créez et gérez les pages du site.' }, media: { title: 'Médias', description: 'Gérez vos médias.' }, theme: { title: 'Thème', description: 'Personnalisez le thème.' } },
  },
} satisfies AuthTranslations;
