import type { Locale } from "@i18n/config";

export interface ServiceFormTranslations {
  sections: { content: string; pricing: string; taxonomy: string; media: string; availability: string; seo: string; settings: string; revisions: string; lock: string };
  fields: { metaTitle: string; metaDescription: string; metaKeywords: string; canonicalUrl: string; ogTitle: string; ogDescription: string; ogImage: string; location: string; address: string; timeZone: string; day: string; start: string; end: string; maxParticipants: string; alt: string; caption: string; order: string };
  actions: { choose: string; remove: string; add: string; update: string; delete: string; refresh: string; release: string; restore: string; publish: string; unpublish: string; archive: string; duplicate: string; lock: string; unlock: string; regenerateSlug: string };
  states: { notSaved: string; noAvailability: string; noMedia: string; noRevisions: string; locked: string; unlocked: string; working: string };
  days: string[];
}

const fr: ServiceFormTranslations = {
  sections: { content: "Contenu", pricing: "Tarification", taxonomy: "Catégories et tags", media: "Médias", availability: "Disponibilités", seo: "SEO", settings: "Paramètres", revisions: "Révisions", lock: "Verrouillage" },
  fields: { metaTitle: "Titre meta", metaDescription: "Description meta", metaKeywords: "Mots-clés meta", canonicalUrl: "URL canonique", ogTitle: "Titre Open Graph", ogDescription: "Description Open Graph", ogImage: "Image Open Graph", location: "Lieu", address: "Adresse", timeZone: "Fuseau horaire", day: "Jour", start: "Début", end: "Fin", maxParticipants: "Participants max.", alt: "Texte alternatif", caption: "Légende", order: "Ordre" },
  actions: { choose: "Choisir", remove: "Retirer", add: "Ajouter", update: "Mettre à jour", delete: "Supprimer", refresh: "Actualiser", release: "Libérer", restore: "Restaurer", publish: "Publier", unpublish: "Dépublier", archive: "Archiver", duplicate: "Dupliquer", lock: "Verrouiller", unlock: "Déverrouiller", regenerateSlug: "Régénérer le slug" },
  states: { notSaved: "Enregistrez le service pour gérer cette section.", noAvailability: "Aucune disponibilité.", noMedia: "Aucun média.", noRevisions: "Aucune révision.", locked: "Service verrouillé pour votre session.", unlocked: "Service déverrouillé.", working: "Traitement…" },
  days: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"],
};
const en: ServiceFormTranslations = { sections: { content: "Content", pricing: "Pricing", taxonomy: "Categories and tags", media: "Media", availability: "Availability", seo: "SEO", settings: "Settings", revisions: "Revisions", lock: "Locking" }, fields: { metaTitle: "Meta title", metaDescription: "Meta description", metaKeywords: "Meta keywords", canonicalUrl: "Canonical URL", ogTitle: "Open Graph title", ogDescription: "Open Graph description", ogImage: "Open Graph image", location: "Location", address: "Address", timeZone: "Time zone", day: "Day", start: "Start", end: "End", maxParticipants: "Max participants", alt: "Alt text", caption: "Caption", order: "Order" }, actions: { choose: "Choose", remove: "Remove", add: "Add", update: "Update", delete: "Delete", refresh: "Refresh", release: "Release", restore: "Restore", publish: "Publish", unpublish: "Unpublish", archive: "Archive", duplicate: "Duplicate", lock: "Lock", unlock: "Unlock", regenerateSlug: "Regenerate slug" }, states: { notSaved: "Save the service to manage this section.", noAvailability: "No availability.", noMedia: "No media.", noRevisions: "No revisions.", locked: "Service locked for your session.", unlocked: "Service unlocked.", working: "Working…" }, days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"] };
const es: ServiceFormTranslations = { sections: { content: "Contenido", pricing: "Precios", taxonomy: "Categorías y etiquetas", media: "Medios", availability: "Disponibilidad", seo: "SEO", settings: "Configuración", revisions: "Revisiones", lock: "Bloqueo" }, fields: { metaTitle: "Título meta", metaDescription: "Descripción meta", metaKeywords: "Palabras clave meta", canonicalUrl: "URL canónica", ogTitle: "Título Open Graph", ogDescription: "Descripción Open Graph", ogImage: "Imagen Open Graph", location: "Ubicación", address: "Dirección", timeZone: "Zona horaria", day: "Día", start: "Inicio", end: "Fin", maxParticipants: "Participantes máx.", alt: "Texto alternativo", caption: "Pie de foto", order: "Orden" }, actions: { choose: "Elegir", remove: "Quitar", add: "Añadir", update: "Actualizar", delete: "Eliminar", refresh: "Actualizar", release: "Liberar", restore: "Restaurar", publish: "Publicar", unpublish: "Despublicar", archive: "Archivar", duplicate: "Duplicar", lock: "Bloquear", unlock: "Desbloquear", regenerateSlug: "Regenerar slug" }, states: { notSaved: "Guarda el servicio para gestionar esta sección.", noAvailability: "Sin disponibilidad.", noMedia: "Sin medios.", noRevisions: "Sin revisiones.", locked: "Servicio bloqueado para tu sesión.", unlocked: "Servicio desbloqueado.", working: "Procesando…" }, days: ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"] };
const ar: ServiceFormTranslations = { sections: { content: "المحتوى", pricing: "التسعير", taxonomy: "الفئات والوسوم", media: "الوسائط", availability: "التوفر", seo: "تحسين محركات البحث", settings: "الإعدادات", revisions: "المراجعات", lock: "القفل" }, fields: { metaTitle: "عنوان Meta", metaDescription: "وصف Meta", metaKeywords: "كلمات Meta", canonicalUrl: "الرابط الأساسي", ogTitle: "عنوان Open Graph", ogDescription: "وصف Open Graph", ogImage: "صورة Open Graph", location: "الموقع", address: "العنوان", timeZone: "المنطقة الزمنية", day: "اليوم", start: "البداية", end: "النهاية", maxParticipants: "الحد الأقصى للمشاركين", alt: "النص البديل", caption: "التعليق", order: "الترتيب" }, actions: { choose: "اختيار", remove: "إزالة", add: "إضافة", update: "تحديث", delete: "حذف", refresh: "تحديث", release: "تحرير", restore: "استعادة", publish: "نشر", unpublish: "إلغاء النشر", archive: "أرشفة", duplicate: "تكرار", lock: "قفل", unlock: "إلغاء القفل", regenerateSlug: "إعادة توليد الرابط المختصر" }, states: { notSaved: "احفظ الخدمة لإدارة هذا القسم.", noAvailability: "لا توجد أوقات متاحة.", noMedia: "لا توجد وسائط.", noRevisions: "لا توجد مراجعات.", locked: "الخدمة مقفلة لجلسة المستخدم الحالية.", unlocked: "تم إلغاء القفل.", working: "جارٍ التنفيذ…" }, days: ["الإثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت", "الأحد"] };

export function getServiceFormTranslations(locale: Locale): ServiceFormTranslations { return locale === "en" ? en : locale === "es" ? es : locale === "ar" ? ar : fr; }
