export type ServiceTranslations = {
  meta: { title: string; description: string };
  labels: { services: string; service: string; search: string; noResults: string; readMore: string; price: string; duration: string; provider: string; category: string; categories: string; mobile: string; participants: string; featured: string; availability: string; reviews: string; favorite: string; unfavorite: string };
  admin: { title: string; newService: string; editService: string; save: string; publish: string; unpublish: string; archive: string; restore: string; duplicate: string; delete: string; preview: string; fields: { title: string; slug: string; excerpt: string; content: string; coverImage: string; price: string; currency: string; duration: string; maxParticipants: string; mobile: string; featured: string; categories: string; tags: string; locale: string; publication: string }; status: Record<string, string> };
};

const translations: Record<string, ServiceTranslations> = {
  fr: { meta: { title: "Services", description: "Découvrez nos services et prestations." }, labels: { services: "Services", service: "Service", search: "Rechercher", noResults: "Aucun service trouvé.", readMore: "Voir le service", price: "Prix", duration: "Durée", provider: "Prestataire", category: "Catégorie", categories: "Catégories", mobile: "À domicile", participants: "Participants", featured: "À la une", availability: "Disponibilités", reviews: "Avis", favorite: "Ajouter aux favoris", unfavorite: "Retirer des favoris" }, admin: { title: "Administration des services", newService: "Nouveau service", editService: "Modifier le service", save: "Enregistrer", publish: "Publier", unpublish: "Dépublier", archive: "Archiver", restore: "Restaurer", duplicate: "Dupliquer", delete: "Supprimer", preview: "Aperçu", fields: { title: "Titre", slug: "Slug", excerpt: "Extrait", content: "Contenu", coverImage: "Image", price: "Prix", currency: "Devise", duration: "Durée (minutes)", maxParticipants: "Participants max.", mobile: "À domicile", featured: "À la une", categories: "Catégories", tags: "Tags", locale: "Langue", publication: "Publication" }, status: { DRAFT: "Brouillon", PUBLISHED: "Publié", ARCHIVED: "Archivé", DELETED: "Supprimé" } } },
  en: { meta: { title: "Services", description: "Discover our services and offerings." }, labels: { services: "Services", service: "Service", search: "Search", noResults: "No services found.", readMore: "View service", price: "Price", duration: "Duration", provider: "Provider", category: "Category", categories: "Categories", mobile: "Mobile service", participants: "Participants", featured: "Featured", availability: "Availability", reviews: "Reviews", favorite: "Add to favorites", unfavorite: "Remove from favorites" }, admin: { title: "Services administration", newService: "New service", editService: "Edit service", save: "Save", publish: "Publish", unpublish: "Unpublish", archive: "Archive", restore: "Restore", duplicate: "Duplicate", delete: "Delete", preview: "Preview", fields: { title: "Title", slug: "Slug", excerpt: "Excerpt", content: "Content", coverImage: "Cover image", price: "Price", currency: "Currency", duration: "Duration (minutes)", maxParticipants: "Max participants", mobile: "Mobile service", featured: "Featured", categories: "Categories", tags: "Tags", locale: "Locale", publication: "Publication" }, status: { DRAFT: "Draft", PUBLISHED: "Published", ARCHIVED: "Archived", DELETED: "Deleted" } } },
  es: { meta: { title: "Servicios", description: "Descubre nuestros servicios y prestaciones." }, labels: { services: "Servicios", service: "Servicio", search: "Buscar", noResults: "No se encontraron servicios.", readMore: "Ver servicio", price: "Precio", duration: "Duración", provider: "Proveedor", category: "Categoría", categories: "Categorías", mobile: "A domicilio", participants: "Participantes", featured: "Destacado", availability: "Disponibilidad", reviews: "Reseñas", favorite: "Añadir a favoritos", unfavorite: "Quitar de favoritos" }, admin: { title: "Administración de servicios", newService: "Nuevo servicio", editService: "Editar servicio", save: "Guardar", publish: "Publicar", unpublish: "Despublicar", archive: "Archivar", restore: "Restaurar", duplicate: "Duplicar", delete: "Eliminar", preview: "Vista previa", fields: { title: "Título", slug: "Slug", excerpt: "Extracto", content: "Contenido", coverImage: "Imagen", price: "Precio", currency: "Moneda", duration: "Duración (minutos)", maxParticipants: "Participantes máx.", mobile: "A domicilio", featured: "Destacado", categories: "Categorías", tags: "Etiquetas", locale: "Idioma", publication: "Publicación" }, status: { DRAFT: "Borrador", PUBLISHED: "Publicado", ARCHIVED: "Archivado", DELETED: "Eliminado" } } },
  ar: { meta: { title: "الخدمات", description: "اكتشف خدماتنا وعروضنا." }, labels: { services: "الخدمات", service: "خدمة", search: "بحث", noResults: "لم يتم العثور على خدمات.", readMore: "عرض الخدمة", price: "السعر", duration: "المدة", provider: "مقدم الخدمة", category: "الفئة", categories: "الفئات", mobile: "خدمة منزلية", participants: "المشاركون", featured: "مميز", availability: "التوفر", reviews: "التقييمات", favorite: "إضافة للمفضلة", unfavorite: "إزالة من المفضلة" }, admin: { title: "إدارة الخدمات", newService: "خدمة جديدة", editService: "تعديل الخدمة", save: "حفظ", publish: "نشر", unpublish: "إلغاء النشر", archive: "أرشفة", restore: "استعادة", duplicate: "تكرار", delete: "حذف", preview: "معاينة", fields: { title: "العنوان", slug: "المعرف", excerpt: "المقتطف", content: "المحتوى", coverImage: "الصورة", price: "السعر", currency: "العملة", duration: "المدة بالدقائق", maxParticipants: "الحد الأقصى", mobile: "خدمة منزلية", featured: "مميز", categories: "الفئات", tags: "الوسوم", locale: "اللغة", publication: "النشر" }, status: { DRAFT: "مسودة", PUBLISHED: "منشور", ARCHIVED: "مؤرشف", DELETED: "محذوف" } } },
};

export function getServiceTranslations(locale: string): ServiceTranslations { return translations[locale] ?? translations.fr; }
